config/routes.rb
Rails.application.routes.draw do
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :description, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rabbit Nutrition Handbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #34D399;">
      <div class="container row row-cols-4">
        <span class="navbar-brand fs-1">Rabbit Nutrition Handbook</span>
        <div></div>
        <div></div>
        <form class="w-100" style="max-width: 575px;">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </nav>
    <div class="text-center px-4 my-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="text-start">
  <div class="row flex-lg-row-reverse align-items-center g-5 py-3">
    <div class="col-10 col-sm-8 col-lg-6 text-center">
      <img class="d-block mx-lg-auto img-fluid" alt="Picture of <%= product.name %>" loading="lazy">
    </div>
    <div class="col-lg-6">
      <h3 class="display-7 fw-bold lh-3 mb-3"> <%= product.name %></h3>
      <p class="lead"><%= product.description %></p>
    </div>
  </div>
</div>

app/views/products/_product_item.html.erb
<div id="<%= dom_id product %>" style="background-color: white;" class="mb-1 card shadow">
  <a style="z-index:1;position:absolute;left:0;top:0;" href="<%= product_path(product)%>" class="w-100 h-100"></a>
  <svg class="bd-placeholder-img card-img-top" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="10%" y="50%" fill="#eceeef" dy=".3em">Preview of <%= product.name %></text></svg>
  <div class="card-body text-start">
    <span class="card-title"><%= product.name %></span>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="album bg-light">
  <div class="container" style="max-width: 950px;">
    <div id="products" class="row row-cols-1 row-cols-sm-2 row-cols-xs-2 row-cols-md-4 g-3">
      <% @products.each do |product| %>
        <div class="col">
          <%= render "product_item", product: product %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="d-inline-flex align-items-start text-start flex-column bd-highlight mb-3">
<h1>New product</h1>
<%= render "form", product: @product %>
</div>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<style>
  a {
    color: var(--bs-body-color);
  }
</style>
<p style="color: green"><%= notice %></p>
<div class="container col-xxl-8 px-4">
  <div class="text-start">
    <%= link_to "Back to products", products_path %>
  </div>

  <%= render @product %>
</div>